# Generated by Django 4.2.6 on 2023-12-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='SecondComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
                ('toComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firstcomment')),
            ],
        ),
    ]
